Update lint.yaml

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -33,7 +33,8 @@ jobs:
       - name: Lint
         id: lint
         run: |
-          echo "Success"
+          echo "Failure"
+          exit 1
 
       - uses: actions/github-script@v7
         if: always()
